# Generated by Django 4.2.5 on 2023-09-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10, verbose_name='login')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('surname', models.CharField(max_length=10, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=30, verbose_name='почта')),
            ],
        ),
    ]
