# Generated by Django 4.2.4 on 2023-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите тип публикуемого обьявления'), ('b', 'Куплю'), ('sell', 'Продам'), ('e', 'Обменяю')], default='sell', max_length=10),
        ),
    ]
